SESSION_ID_KEY_LENGTH: int = 32
SESSION_ID_PAYLOAD_POSITION: slice = slice(0, 32)
ISSUED_AT_PAYLOAD_POSITION: slice = slice(32, 40)
FINGERPRINT_PAYLOD_POSITION: slice = slice(40)
SIGNATURE_LENGTH: int = 32
_ISSUED_AT_LENGTH: int = 8
TOKEN_MAX_LENGTH = SESSION_ID_KEY_LENGTH + _ISSUED_AT_LENGTH + SIGNATURE_LENGTH
